//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Nullable<int> custid { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> ProId { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> mrp { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
