//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerInfo
    {
        public int CustId { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string CustName { get; set; }


        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address or Email already registered.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Country is required.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string Country { get; set; }


        [Required(ErrorMessage = "Contact is required.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Contact must have numbers only")]
        [MaxLength(10, ErrorMessage = "Cannot exceed 10 digits")]
        [MinLength(10, ErrorMessage = "Cannot be less than 10 digits")]
        public string Contact { get; set; }


        [MinLength(6, ErrorMessage = "Cannot be less than 6 digits")]
        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; }

        [Required(ErrorMessage = "PinCode is required.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "PinCode should be numbers only")]
        [MaxLength(6, ErrorMessage = "PinCode cannot exceed 6 digits")]
        [MinLength(6, ErrorMessage = "PinCode cannot be less than 6 digits")]
        public string PinCode { get; set; }
    }
}
