//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CapstoneDatabaseEntities : DbContext
    {
        public CapstoneDatabaseEntities()
            : base("name=CapstoneDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<OrderInfo> OrderInfoes { get; set; }
        public virtual DbSet<OrderItemInfo> OrderItemInfoes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<ipv6_database_firewall_rules> ipv6_database_firewall_rules { get; set; }
    
        public virtual int addcustomer(string custName, string email, string pincode, string country, string contact, string password)
        {
            var custNameParameter = custName != null ?
                new ObjectParameter("CustName", custName) :
                new ObjectParameter("CustName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("Pincode", pincode) :
                new ObjectParameter("Pincode", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addcustomer", custNameParameter, emailParameter, pincodeParameter, countryParameter, contactParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> cartsum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("cartsum");
        }
    
        public virtual int copyintoorderiteminfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("copyintoorderiteminfo");
        }
    
        public virtual int deletefromcart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletefromcart");
        }
    
        public virtual ObjectResult<getcustomerbyemail_Result> getcustomerbyemail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getcustomerbyemail_Result>("getcustomerbyemail", emailParameter);
        }
    
        public virtual ObjectResult<getorderiteminfobycode_Result> getorderiteminfobycode(Nullable<int> custid)
        {
            var custidParameter = custid.HasValue ?
                new ObjectParameter("custid", custid) :
                new ObjectParameter("custid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getorderiteminfobycode_Result>("getorderiteminfobycode", custidParameter);
        }
    
        public virtual ObjectResult<getproductsbycategory_Result> getproductsbycategory(string category)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getproductsbycategory_Result>("getproductsbycategory", categoryParameter);
        }
    
        public virtual int insertintoOrderInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertintoOrderInfo");
        }
    
        public virtual ObjectResult<validateuser_Result> validateuser(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<validateuser_Result>("validateuser", emailParameter, passwordParameter);
        }
    }
}
