//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
        }

        [Required(ErrorMessage = "Product ID is required.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Product ID must have numbers only")]
        public int ProId { get; set; }

        [Required(ErrorMessage = "Product Name is required.")]
        public string ProName { get; set; }

        [Required(ErrorMessage = "Brand Name is required.")]
        public string BrandName { get; set; }

        [Required(ErrorMessage = "Product Cateogry is required.")]
        public string Category { get; set; }

        [Required(ErrorMessage = "MRP is required.")]
        [Range(0, 9999999999999999.99, ErrorMessage = "Please enter a valid decimal Number with 2 decimal places")]
        public Nullable<decimal> mrp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
